name: Sync files from R2

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  R2_To_GitHub :
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Sync files to GitHub
      continue-on-error: true
      uses: fscarmen2/r2_to_github@v1.0.0
      with:
        delete_from_r2: true